name: witofthestaircase
favicon: null
layout_spectrum: 0.26873
typography_spectrum: 0.8748118081130087
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0
  lightness: 0.29728605411946774
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
