name: witofthestaircase
favicon: null
layout_spectrum: 0
typography_spectrum: 0.99769
title: 'The experience that one’s sharpest retorts occur to one only when the chance of uttering them is gone, the door is closed, and one’s feet are half way up the staircase. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5
  lightness: 0.29728605411946774
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
